import getConfig from 'next/config';
import Head from 'next/head';
import { Content } from '../components/content';
import { Description } from '../components/description';
import { Evidence } from '../components/evidence';
import { Partners } from '../components/partners';
import { Plans } from '../components/plans';
import { Register } from '../components/register';

export default function Home() {
  const { publicRuntimeConfig } = getConfig();
  return (
    <>
      <Head>
        <title>Health+</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={`${publicRuntimeConfig.baseUrl}/img/favicon.ico`} />
      </Head>
      <main>
        <Content>
          <Description />
          <Plans />
          <Evidence />
          <Register />
          <Partners />
        </Content>
      </main>
    </>
  );
};
